"""
Codegen — Backend API: Express CRUD router/controller/service generation.

Extracted from engine/skills/executor.py (Phase 2).
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


async def _build_backend_api_code(
    db: Any,
    project_id: str,
) -> dict[str, str] | None:
    """API 설계서 + DB 설계서 → Express CRUD 라우터/컨트롤러/서비스 (AI 0회).

    Returns:
        {"server": "...", "router-users": "...", ...} or None
    """
    from engine.skills.artifact.loader import _load_api_spec_parsed, _load_db_spec_parsed

    api_spec = await _load_api_spec_parsed(db, project_id)
    db_spec = await _load_db_spec_parsed(db, project_id)

    if not api_spec["endpoints"]:
        logger.warning("backend_api_gen_skip project=%s — API 설계서 없음", project_id)
        return None

    # 엔드포인트를 리소스별로 그룹화
    resources: dict[str, list[dict]] = {}
    for ep in api_spec["endpoints"]:
        # /api/v1/users/:id → "users"
        path_parts = [p for p in ep["path"].split("/") if p and p != "api" and not p.startswith("v")]
        res_name = path_parts[0] if path_parts else "root"
        resources.setdefault(res_name, []).append(ep)

    result: dict[str, str] = {}

    # ── server.ts (엔트리포인트) ──
    result["server"] = _generate_express_server(list(resources.keys()))

    # ── 리소스별 라우터 + 서비스 ──
    for res_name, endpoints in resources.items():
        matched_table = None
        for tname, tdata in db_spec["tables"].items():
            if res_name.replace("-", "").replace("_", "") in tname.replace("_", "").lower():
                matched_table = (tname, tdata)
                break

        router_code = _generate_express_router(res_name, endpoints, matched_table)
        result[f"router-{res_name}"] = router_code

        service_code = _generate_express_service(res_name, endpoints, matched_table)
        result[f"service-{res_name}"] = service_code

    # ── 공통 미들웨어 ──
    result["middleware-auth"] = _generate_auth_middleware()
    result["middleware-error"] = _generate_error_middleware()

    logger.info(
        "backend_api_code_built project=%s resources=%d endpoints=%d files=%d",
        project_id, len(resources), len(api_spec["endpoints"]), len(result),
    )
    return result


def _generate_express_server(resource_names: list[str]) -> str:
    """Express server.ts 엔트리포인트."""
    L = []
    L.append("// FILE: src/server.ts")
    L.append("// GENERATED BY: programmatic-assembler (AI 0 calls)")
    L.append("import express from 'express';")
    L.append("import cors from 'cors';")
    L.append("import helmet from 'helmet';")
    L.append("import compression from 'compression';")
    L.append("import dotenv from 'dotenv';")
    L.append("import { PrismaClient } from '@prisma/client';")
    L.append("import { errorHandler } from './middleware/errorHandler';")
    L.append("")
    for res in resource_names:
        safe = res.replace("-", "_")
        L.append(f"import {{ {safe}Router }} from './routes/{safe}';")
    L.append("")
    L.append("dotenv.config();")
    L.append("")
    L.append("const app = express();")
    L.append("const prisma = new PrismaClient();")
    L.append("const PORT = process.env.PORT || 4000;")
    L.append("")
    L.append("// Middleware")
    L.append("app.use(helmet());")
    L.append("app.use(compression());")
    L.append("app.use(cors({ origin: process.env.CORS_ORIGIN || '*' }));")
    L.append("app.use(express.json());")
    L.append("")
    L.append("// Prisma 인스턴스를 req에 주입")
    L.append("app.use((req: any, _res, next) => {")
    L.append("  req.prisma = prisma;")
    L.append("  next();")
    L.append("});")
    L.append("")
    L.append("// Routes")
    for res in resource_names:
        safe = res.replace("-", "_")
        L.append(f"app.use('/api/v1/{res}', {safe}Router);")
    L.append("")
    L.append("// Health check")
    L.append("app.get('/', (_req, res) => res.json({ status: 'ok' }));")
    L.append("")
    L.append("// Error handler (must be last)")
    L.append("app.use(errorHandler);")
    L.append("")
    L.append("app.listen(PORT, () => {")
    L.append(f"  console.log(`Server running on port ${{PORT}}`);")
    L.append("});")
    L.append("")
    L.append("export { app, prisma };")
    return "\n".join(L)


def _generate_express_router(
    res_name: str,
    endpoints: list[dict],
    matched_table: tuple | None,
) -> str:
    """리소스별 Express 라우터."""
    safe = res_name.replace("-", "_")
    pascal = "".join(w.capitalize() for w in res_name.replace("-", "_").split("_"))
    service_name = f"{safe}Service"

    L = []
    L.append(f"// FILE: src/routes/{safe}.ts")
    L.append("// GENERATED BY: programmatic-assembler (AI 0 calls)")
    L.append("import { Router, Request, Response, NextFunction } from 'express';")
    L.append(f"import * as {service_name} from '../services/{safe}';")
    L.append("")
    L.append(f"export const {safe}Router = Router();")
    L.append("")

    for ep in endpoints:
        method = ep["method"].lower()
        path = ep["path"]
        desc = ep.get("description", "")

        # /api/v1/users/:id → /:id, /api/v1/users → /
        rel_path = path
        prefix = f"/api/v1/{res_name}"
        prefix_alt = f"/api/{res_name}"
        if rel_path.startswith(prefix):
            rel_path = rel_path[len(prefix):] or "/"
        elif rel_path.startswith(prefix_alt):
            rel_path = rel_path[len(prefix_alt):] or "/"

        # Express 파라미터 변환: {id} → :id
        rel_path = rel_path.replace("{id}", ":id").replace("{", ":").replace("}", "")

        # 핸들러명 결정
        has_id = ":id" in rel_path or ":id" in path
        if method == "get" and not has_id:
            handler = "getAll"
        elif method == "get" and has_id:
            handler = "getById"
        elif method == "post":
            handler = "create"
        elif method in ("put", "patch"):
            handler = "update"
        elif method == "delete":
            handler = "remove"
        else:
            handler = f"{method}Handler"

        L.append(f"// {desc}")
        L.append(f"{safe}Router.{method}('{rel_path}', async (req: Request, res: Response, next: NextFunction) => {{")
        L.append("  try {")
        if has_id:
            L.append("    const { id } = req.params;")
            if method in ("put", "patch"):
                L.append(f"    const result = await {service_name}.{handler}((req as any).prisma, id, req.body);")
            elif method == "delete":
                L.append(f"    const result = await {service_name}.{handler}((req as any).prisma, id);")
            else:
                L.append(f"    const result = await {service_name}.{handler}((req as any).prisma, id);")
        elif method == "post":
            L.append(f"    const result = await {service_name}.{handler}((req as any).prisma, req.body);")
        else:
            # GET list — 쿼리파라미터
            L.append("    const { page = '1', q = '', limit = '20' } = req.query as Record<string, string>;")
            L.append(f"    const result = await {service_name}.{handler}((req as any).prisma, {{ page: +page, q, limit: +limit }});")
        L.append("    res.json({ data: result });")
        L.append("  } catch (e) {")
        L.append("    next(e);")
        L.append("  }")
        L.append("});")
        L.append("")

    return "\n".join(L)


def _generate_express_service(
    res_name: str,
    endpoints: list[dict],
    matched_table: tuple | None,
) -> str:
    """리소스별 Prisma 서비스 (CRUD 로직)."""
    safe = res_name.replace("-", "_")
    pascal = "".join(w.capitalize() for w in res_name.replace("-", "_").split("_"))

    # Prisma 모델명 추정
    if matched_table:
        model_name = "".join(w.capitalize() for w in matched_table[0].replace("-", "_").split("_"))
    else:
        model_name = pascal

    # prisma 호출 시 소문자 시작 (Prisma convention)
    prisma_model = model_name[0].lower() + model_name[1:] if model_name else safe

    L = []
    L.append(f"// FILE: src/services/{safe}.ts")
    L.append("// GENERATED BY: programmatic-assembler (AI 0 calls)")
    L.append("import { PrismaClient } from '@prisma/client';")
    L.append("")

    # 어떤 CRUD 오퍼레이션이 필요한지 endpoint에서 파악
    has_list = any(ep["method"] == "GET" and "{" not in ep["path"] and ":" not in ep["path"] for ep in endpoints)
    has_detail = any(ep["method"] == "GET" and ("{" in ep["path"] or ":" in ep["path"]) for ep in endpoints)
    has_create = any(ep["method"] == "POST" for ep in endpoints)
    has_update = any(ep["method"] in ("PUT", "PATCH") for ep in endpoints)
    has_delete = any(ep["method"] == "DELETE" for ep in endpoints)

    if has_list:
        L.append("export async function getAll(")
        L.append("  prisma: PrismaClient,")
        L.append("  params: { page: number; q: string; limit: number },")
        L.append(") {")
        L.append("  const { page, q, limit } = params;")
        L.append("  const skip = (page - 1) * limit;")
        # 검색 조건: 테이블에 name/title 컬럼이 있으면 사용
        search_col = _find_search_column(matched_table)
        if search_col:
            L.append(f"  const where = q ? {{ {search_col}: {{ contains: q }} }} : {{}};")
        else:
            L.append("  const where = {};")
        L.append(f"  const [items, total] = await Promise.all([")
        L.append(f"    prisma.{prisma_model}.findMany({{ where, skip, take: limit, orderBy: {{ createdAt: 'desc' }} }}),")
        L.append(f"    prisma.{prisma_model}.count({{ where }}),")
        L.append("  ]);")
        L.append("  return { items, total, page, pageSize: limit };")
        L.append("}")
        L.append("")

    if has_detail:
        L.append("export async function getById(prisma: PrismaClient, id: string) {")
        L.append(f"  const item = await prisma.{prisma_model}.findUnique({{ where: {{ id }} }});")
        L.append("  if (!item) throw Object.assign(new Error('Not found'), { status: 404 });")
        L.append("  return item;")
        L.append("}")
        L.append("")

    if has_create:
        L.append("export async function create(prisma: PrismaClient, data: any) {")
        L.append(f"  return prisma.{prisma_model}.create({{ data }});")
        L.append("}")
        L.append("")

    if has_update:
        L.append("export async function update(prisma: PrismaClient, id: string, data: any) {")
        L.append(f"  return prisma.{prisma_model}.update({{ where: {{ id }}, data }});")
        L.append("}")
        L.append("")

    if has_delete:
        L.append("export async function remove(prisma: PrismaClient, id: string) {")
        L.append(f"  return prisma.{prisma_model}.delete({{ where: {{ id }} }});")
        L.append("}")
        L.append("")

    return "\n".join(L)


def _find_search_column(matched_table: tuple | None) -> str:
    """검색 대상 컬럼 추정: name, title, email, content 순."""
    if not matched_table:
        return ""
    cols = {c["name"].lower() for c in matched_table[1].get("columns", [])}
    for candidate in ("name", "title", "email", "content", "description", "subject"):
        if candidate in cols:
            return candidate
    return ""


def _generate_auth_middleware() -> str:
    """JWT 인증 미들웨어."""
    return """// FILE: src/middleware/auth.ts
// GENERATED BY: programmatic-assembler (AI 0 calls)
import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

const JWT_SECRET = process.env.JWT_ACCESS_SECRET || 'dev-secret';

export interface AuthRequest extends Request {
  user?: { id: string; email: string; role: string };
}

export function authGuard(req: AuthRequest, res: Response, next: NextFunction) {
  const header = req.headers.authorization;
  if (!header?.startsWith('Bearer ')) {
    return res.status(401).json({ error: '인증 토큰이 필요합니다' });
  }

  try {
    const token = header.slice(7);
    const decoded = jwt.verify(token, JWT_SECRET) as AuthRequest['user'];
    req.user = decoded;
    next();
  } catch {
    return res.status(401).json({ error: '유효하지 않은 토큰입니다' });
  }
}
"""


def _generate_error_middleware() -> str:
    """전역 에러 핸들러."""
    return """// FILE: src/middleware/errorHandler.ts
// GENERATED BY: programmatic-assembler (AI 0 calls)
import { Request, Response, NextFunction } from 'express';

export function errorHandler(err: any, _req: Request, res: Response, _next: NextFunction) {
  const status = err.status || 500;
  const message = err.message || '서버 오류가 발생했습니다';

  console.error(`[ERROR] ${status} ${message}`, err.stack ? err.stack.split('\\n')[1] : '');

  res.status(status).json({
    error: message,
    ...(process.env.NODE_ENV === 'development' && { stack: err.stack }),
  });
}
"""
