"""
Codegen — DB schema: Prisma schema + SQL migration generation.

Extracted from engine/skills/executor.py (Phase 2).
"""

from __future__ import annotations

import logging
from typing import Any

from engine.skills.codegen.helpers import _sql_to_prisma_type

logger = logging.getLogger(__name__)


async def _build_db_schema_code(
    db: Any,
    project_id: str,
) -> dict[str, str] | None:
    """DB 설계서(ERD) → Prisma schema + SQL migration 직역 (AI 0회).

    Returns:
        {"prisma-schema": "...", "migration": "..."} or None (설계서 없음)
    """
    from engine.skills.artifact.loader import _load_db_spec_parsed

    db_spec = await _load_db_spec_parsed(db, project_id)
    if not db_spec["tables"]:
        logger.warning("db_schema_gen_skip project=%s — DB 설계서 없음", project_id)
        return None

    result: dict[str, str] = {}

    # ── Prisma Schema ──
    prisma = _generate_prisma_schema(db_spec["tables"])
    result["prisma-schema"] = prisma

    # ── SQL Migration ──
    sql = _generate_sql_migration(db_spec["tables"])
    result["migration"] = sql

    logger.info(
        "db_schema_code_built project=%s tables=%d prisma=%d sql=%d",
        project_id, len(db_spec["tables"]), len(prisma), len(sql),
    )
    return result


def _generate_prisma_schema(tables: dict[str, dict]) -> str:
    """테이블 정의 → Prisma schema.prisma 생성."""
    L = []
    L.append("// FILE: prisma/schema.prisma")
    L.append("// GENERATED BY: programmatic-assembler (AI 0 calls)")
    L.append("")
    L.append("generator client {")
    L.append('  provider = "prisma-client-js"')
    L.append("}")
    L.append("")
    L.append("datasource db {")
    L.append('  provider = "sqlite"')
    L.append('  url      = env("DATABASE_URL")')
    L.append("}")
    L.append("")

    # 모든 테이블 이름 수집 (relation 판별용)
    all_table_names = {t.lower() for t in tables}
    # 단수→복수, 복수→단수 매핑
    _model_name_map: dict[str, str] = {}
    for tname in tables:
        pascal = "".join(w.capitalize() for w in tname.replace("-", "_").split("_"))
        _model_name_map[tname.lower()] = pascal

    for tname, tdata in tables.items():
        model_name = _model_name_map.get(tname.lower(), tname.capitalize())
        L.append(f"model {model_name} {{")

        columns = tdata.get("columns", [])
        # relation 후보 수집
        fk_targets: list[tuple[str, str]] = []  # (col_name, target_table)

        for col in columns:
            cname = col["name"]
            ctype = col.get("type", "TEXT").upper()
            is_pk = col.get("pk", False)
            nullable = col.get("nullable", True)
            is_fk = col.get("fk", False)

            # Prisma 타입 매핑
            if is_pk and cname == "id":
                L.append(f"  {cname}  String  @id @default(cuid())")
                continue

            prisma_type = _sql_to_prisma_type(ctype)

            attrs = []
            if is_pk:
                attrs.append("@id")
            if cname in ("created_at", "createdAt"):
                attrs.append("@default(now())")
            elif cname in ("updated_at", "updatedAt"):
                attrs.append("@updatedAt")
            elif is_pk and prisma_type == "Int":
                attrs.append("@id @default(autoincrement())")

            # FK 감지: _id 접미사 + 대상 테이블 존재
            if is_fk or cname.endswith("_id") or cname.endswith("Id"):
                ref_name = cname.replace("_id", "").replace("Id", "")
                # 복수형 시도
                for candidate in [ref_name, ref_name + "s", ref_name + "es"]:
                    if candidate.lower() in all_table_names:
                        fk_targets.append((cname, candidate.lower()))
                        break

            opt = "?" if nullable and not is_pk else ""
            attr_str = "  " + " ".join(attrs) if attrs else ""
            L.append(f"  {cname}  {prisma_type}{opt}{attr_str}")

        # Relation 필드 추가
        for fk_col, target_table in fk_targets:
            ref_model = _model_name_map.get(target_table, target_table.capitalize())
            rel_field = fk_col.replace("_id", "").replace("Id", "")
            L.append(f"  {rel_field}  {ref_model}  @relation(fields: [{fk_col}], references: [id])")

        L.append("}")
        L.append("")

    return "\n".join(L)


def _generate_sql_migration(tables: dict[str, dict]) -> str:
    """테이블 정의 → SQLite CREATE TABLE migration."""
    L = []
    L.append("// FILE: prisma/migrations/001_init/migration.sql")
    L.append("-- GENERATED BY: programmatic-assembler (AI 0 calls)")
    L.append("")

    for tname, tdata in tables.items():
        columns = tdata.get("columns", [])
        L.append(f"CREATE TABLE IF NOT EXISTS {tname} (")

        col_defs = []
        for col in columns:
            cname = col["name"]
            ctype = col.get("type", "TEXT").upper()
            is_pk = col.get("pk", False)
            nullable = col.get("nullable", True)
            is_fk = col.get("fk", False)

            parts = [f"  {cname}", ctype]
            if is_pk:
                parts.append("PRIMARY KEY")
            if not nullable and not is_pk:
                parts.append("NOT NULL")
            if cname in ("created_at", "createdAt"):
                parts.append("DEFAULT CURRENT_TIMESTAMP")

            col_defs.append(" ".join(parts))

        # FK constraints
        for col in columns:
            if col.get("fk") or col["name"].endswith("_id") or col["name"].endswith("Id"):
                ref_name = col["name"].replace("_id", "").replace("Id", "")
                for candidate in [ref_name, ref_name + "s", ref_name + "es"]:
                    if candidate.lower() in {t.lower() for t in tables}:
                        col_defs.append(
                            f"  FOREIGN KEY ({col['name']}) REFERENCES {candidate}(id)"
                        )
                        break

        L.append(",\n".join(col_defs))
        L.append(");")
        L.append("")

    return "\n".join(L)
