from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def _build_generic_page(
    slug: str, recipe, sorted_placements: list, _pascal,
) -> list[str]:
    """기타 플랫폼: 구조화된 placement 목록."""
    L = [f"// PAGE: {slug} ({recipe.page_name})"]  # noqa: E741
    L.append(f"// layout: {recipe.layout}")
    L.append(f"// GENERATED BY: placement-assembler (DO NOT modify structure)")
    L.append(f"//")
    L.append(f"// ── UX Placements (자동 생성) ──")
    for p in sorted_placements:
        if p.order < 0 or p.order > 8999:
            cond = f" [if {p.condition}]" if p.condition else ""
            L.append(f"// UX: {p.component_name} (order={p.order}){cond}")
    L.append(f"//")
    L.append(f"// ── Content Placements ──")
    for p in sorted_placements:
        if 0 <= p.order <= 8999:
            cond = f" [if {p.condition}]" if p.condition else ""
            repeat = f" [repeat {p.repeat}]" if p.repeat else ""
            L.append(f"// placement: {p.component_name} (order={p.order}){cond}{repeat}")
    L.append(f"//")
    L.append(f"// AI 담당: data fetching + event handlers + 비즈니스 로직만 구현")
    return L
