from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def _build_vue_page(
    slug: str,
    recipe,
    page_name: str,
    all_imports: list[str],
    content_imports: list[str],
    content_placements: list,
    data_sources: set[str],
    loading_p: list, error_p: list, empty_p: list,
    toast_p: list, modal_p: list,
    _pascal,
) -> list[str]:
    """Vue/Nuxt 완성형 페이지 골격 생성 (AI 0회)."""
    L = []  # noqa: E741

    # ── template ──
    L.append(f"<!-- FILE: src/pages/{page_name}Page.vue -->")
    L.append(f"<!-- GENERATED BY: placement-assembler (DO NOT modify structure) -->")
    L.append(f"<template>")
    L.append(f"  <div class=\"page-{slug} layout-{recipe.layout}\">")

    # loading
    L.append(f"    <!-- Loading (구조 확정) -->")
    L.append(f"    <LoadingIndicator v-if=\"loading\" />")

    # error
    L.append(f"    <!-- Error (구조 확정) -->")
    L.append(f"    <ErrorBoundary v-else-if=\"error\" :error=\"error\" @retry=\"fetchData\" />")

    # empty
    has_empty = " || ".join(f"!data?.{s}?.length" for s in sorted(data_sources)) if data_sources else "!data"
    L.append(f"    <!-- Empty (구조 확정) -->")
    L.append(f"    <EmptyState v-else-if=\"{has_empty}\" @action=\"fetchData\" />")

    # 콘텐츠
    L.append(f"    <!-- Content placements (구조 확정) -->")
    L.append(f"    <template v-else>")
    for p in content_placements:
        pc = _pascal(p.component_name)
        if p.condition:
            cond = p.condition.replace("if ", "").replace("unless ", "!").strip()
            L.append(f"      <{pc} v-if=\"{cond}\" />")
        elif p.repeat:
            L.append(f"      <{pc} v-for=\"(item, i) in {p.repeat}\" :key=\"i\" v-bind=\"item\" />")
        else:
            props = ""
            for b in p.bindings[:5]:
                if b.source_path:
                    props += f" :{b.slot_name}=\"data?.{b.source_path}\""
                elif b.value is not None:
                    props += f" {b.slot_name}=\"{b.value}\""
            L.append(f"      <{pc}{props} />")

    L.append(f"    </template>")

    # toast + modal
    L.append(f"    <!-- Toast Portal (구조 확정) -->")
    L.append(f"    <ToastContainer :message=\"toastMessage\" @close=\"toastMessage = null\" />")
    L.append(f"    <!-- Modal Portal (구조 확정) -->")
    L.append(f"    <ModalContainer :open=\"modalOpen\" @close=\"modalOpen = false\">")
    L.append(f"      <!-- AI: 모달 콘텐츠 구현 -->")
    L.append(f"    </ModalContainer>")
    L.append(f"  </div>")
    L.append(f"</template>")
    L.append(f"")

    # ── script ──
    L.append(f"<script setup lang=\"ts\">")
    L.append(f"import {{ ref, onMounted }} from 'vue';")
    comp_list = ", ".join(all_imports)
    L.append(f"import {{ {comp_list} }} from '@/components';")
    L.append(f"")
    L.append(f"const loading = ref(true);")
    L.append(f"const error = ref<Error | null>(null);")
    L.append(f"const data = ref<any>(null);")
    L.append(f"const toastMessage = ref<string | null>(null);")
    L.append(f"const modalOpen = ref(false);")
    L.append(f"")
    L.append(f"async function fetchData() {{")
    L.append(f"  try {{")
    L.append(f"    loading.value = true;")
    L.append(f"    error.value = null;")
    L.append(f"    /* AI: API 호출 구현 */")
    L.append(f"  }} catch (e) {{")
    L.append(f"    error.value = e instanceof Error ? e : new Error(String(e));")
    L.append(f"  }} finally {{")
    L.append(f"    loading.value = false;")
    L.append(f"  }}")
    L.append(f"}}")
    L.append(f"")
    L.append(f"/* AI: 이벤트 핸들러 구현 */")
    L.append(f"")
    L.append(f"onMounted(fetchData);")
    L.append(f"</script>")

    return L
